AdminClient:
  client_id: oai-admin-alex-producer
OAI:
  set: Sbib_OAI
  timestampUTC: '2020-03-21T01:01:01Z'
  url: https://eu.alma.exlibrisgroup.com/view/oai/41BIG_INST/request
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-alexandria-producer
Topic:
  name: cc-alex