AdminClient:
  client_id: oai-admin-eperiodica-producer
OAI:
  timestampUTC: '2020-03-21T01:01:01Z'
  url: http://www.e-periodica.ch/oai/dataprovider
  metadataPrefix: oai_dc
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-eperiodica-producer
Topic:
  name: cc-eperiodica
