AdminClient:
  client_id: oai-admin-hemu-producer
OAI:
  set: marcxml
  timestampUTC: '2019-05-16T01:01:01Z'
  url: http://opacbiblio.hemu-cl.ch/cgi-bin/koha/oai.pl
  metadataPrefix: marcxml
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-hemu-producer
Topic:
  name: cc-hemu
