AdminClient:
  client_id: oai-admin-idsbb-producer
OAI:
  set: SWISSBIB-FULL-OAI
  timestampUTC: '2020-03-21T01:01:01Z'
  url: http://aleph.unibas.ch/OAI
Processing:
  Default:
    stoppageTime: '2019-01-25T11:38:27Z'
Producer:
  client_id: oai-idsbb-producer
Topic:
  name: cc-idsbb
