AdminClient:
  client_id: oai-admin-idssg-producer
OAI:
  set: SWISSBIB-FULL-HSB01
  timestampUTC: '2019-05-16T01:01:01Z'
  url: http://aleph.unisg.ch/cgi-bin/OAI
Processing:
  Default:
    stoppageTime: '2019-02-15T09:59:29Z'
Producer:
  client_id: oai-idssg-producer
Topic:
  name: cc-idssg
