AdminClient:
  client_id: oai-admin-vaud-lib-producer
OAI:
  set: SwisOAI
  timestampUTC: '2020-03-21T01:01:01Z'
  url: https://eu01.alma.exlibrisgroup.com/view/oai/41BCULAUSA_LIB/request
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-vaud-lib-producer
Topic:
  name: cc-vaud
