from kafka_event_hub.producers.eduplatform.edu_zem_kafka import EduZemKafka
from kafka_event_hub.producers.eduplatform.edu_zem_file import EduZemFile
from kafka_event_hub.producers.eduplatform.edu_evento_kafka import EduEventoKafka
from kafka_event_hub.producers.eduplatform.edu_phbern_kafka import EduPHBernKafka