AdminClient:
  client_id: webdav-admin-rero-producer
Processing:
  Default:
    recordBodyRegEx: <record><header.*?>.*?</metadata></record>
    stoppageTime: '2019-02-15T09:50:58Z'
Producer:
  client_id: webdav-rero-producer
Topic:
  name: cc-rero
WebDav:
  basedirwebdav: '/webdav'
  latestProcDate: '2019_02_16'
  processMode: ONLY_NEW_DELIVERD
  singleRecordIterator: <record><header.*?>.*?</metadata></record>
  srcDir: '{basedir}/rero-src'
  workingDir: '{basedir}/rero-working'
