from kafka_event_hub.consumers.eduplatform.zem_consumer import ZemConsumer
import kafka_event_hub.consumers.eduplatform.zem_es_transformation
from kafka_event_hub.consumers.eduplatform.evento_consumer import EventoConsumer

import kafka_event_hub.consumers.eduplatform.evento_es_transformation

